import type { LearningSentence } from "../domain/content-schema";

type Draft = readonly [
  suffix: string,
  role: "production" | "reception",
  english: string,
  chinese: string,
  usageZh: string,
  keywords: readonly string[],
  chunks?: readonly string[],
  phraseSuffix?: string
];

function pack(missionId: string, drafts: readonly Draft[]): LearningSentence[] {
  return drafts.map(([suffix, role, english, chinese, usageZh, keywords, chunks, phraseSuffix]) => ({
    id: `${missionId}-learn-${suffix}`,
    role,
    english,
    chinese,
    usageZh,
    keywords: [...keywords],
    chunks: [...(chunks ?? [english])],
    ...(phraseSuffix ? { phraseId: `${missionId}-${phraseSuffix}` } : {})
  }));
}

export const learningSentencesByMission = {
  "hotel-checkin": pack("hotel-checkin", [
    ["reservation", "production", "I have a reservation.", "我有预订。", "到前台先说明已经预订。", ["reservation"], ["I have", "a reservation"], "reservation"],
    ["name", "production", "The name is Li.", "预订姓名是李。", "工作人员询问姓名时使用。", ["name", "Li"], ["The name is", "Li"], "name"],
    ["room-ready", "production", "Is the room ready?", "房间准备好了吗？", "提前抵达或等待入住时询问。", ["room", "ready"], ["Is the room", "ready"], "room"],
    ["key-cards", "production", "May I have two key cards?", "可以给我两张房卡吗？", "同行时请求额外房卡。", ["two", "key cards"], ["May I have", "two key cards"], "key"],
    ["wifi", "production", "Could you show me the Wi-Fi password?", "可以给我看一下 Wi-Fi 密码吗？", "没听清密码时请对方展示。", ["show", "Wi-Fi", "password"], ["Could you show me", "the Wi-Fi password"], "wifi"],
    ["luggage", "production", "Can you store my luggage?", "可以寄存我的行李吗？", "入住前或退房后寄存行李。", ["store", "luggage"], ["Can you store", "my luggage"]],
    ["late-checkout", "production", "Can I check out later?", "我可以晚一点退房吗？", "需要延迟退房时询问。", ["check out", "later"], ["Can I check out", "later"]],
    ["speak-slowly", "production", "Could you speak more slowly?", "可以说慢一点吗？", "听不清工作人员时使用。", ["speak", "slowly"], ["Could you speak", "more slowly"]],
    ["passport", "reception", "May I see your passport, please?", "可以看一下您的护照吗？", "前台核对入住身份。", ["passport"], ["May I see", "your passport, please"]],
    ["not-ready", "reception", "Your room is not ready yet.", "您的房间还没有准备好。", "提前抵达时常见回答。", ["room", "not ready"], ["Your room", "is not ready yet"]],
    ["ready-three", "reception", "It will be ready after three.", "三点以后会准备好。", "听懂可以入住的时间。", ["ready", "after three"], ["It will be ready", "after three"]],
    ["breakfast", "reception", "Breakfast is from seven to ten.", "早餐时间是七点到十点。", "确认早餐时间范围。", ["breakfast", "seven", "ten"], ["Breakfast is", "from seven to ten"]],
    ["wifi-card", "reception", "The Wi-Fi password is on your key card.", "Wi-Fi 密码在房卡上。", "工作人员可能让你查看房卡。", ["Wi-Fi", "key card"], ["The Wi-Fi password", "is on your key card"]],
    ["bags-here", "reception", "You can leave your bags here.", "您可以把行李放在这里。", "确认寄存位置。", ["bags", "here"], ["You can leave", "your bags here"]],
    ["checkout-eleven", "reception", "Check-out is at eleven.", "退房时间是十一点。", "听懂标准退房时间。", ["check-out", "eleven"], ["Check-out is", "at eleven"]],
    ["lift-left", "reception", "The lift is on your left.", "电梯在您的左边。", "前台说明电梯方向。", ["lift", "left"], ["The lift is", "on your left"]]
  ]),
  restaurant: pack("restaurant", [
    ["table", "production", "A table for two, please.", "请给我们两个人的桌子。", "进入餐厅时说明人数。", ["table", "two"], ["A table", "for two, please"], "table"],
    ["menu", "production", "May I see the menu?", "可以看一下菜单吗？", "没有拿到菜单时询问。", ["see", "menu"], ["May I see", "the menu"], "menu"],
    ["order", "production", "I would like this pasta.", "我想要这份意面。", "指着菜单点餐。", ["like", "pasta"], ["I would like", "this pasta"], "order"],
    ["water", "production", "Still water, please.", "请给我不带气的水。", "区分不带气和气泡水。", ["still", "water"], ["Still water", "please"], "water"],
    ["allergy", "production", "I have a nut allergy.", "我对坚果过敏。", "点餐前明确说明过敏。", ["nut", "allergy"], ["I have", "a nut allergy"], "allergy"],
    ["bill", "production", "Could I have the bill, please?", "请给我账单。", "用餐结束后结账。", ["bill", "please"], ["Could I have", "the bill, please"], "bill"],
    ["say-again", "production", "Could you say that again?", "可以再说一遍吗？", "没有听清菜名或问题时使用。", ["say", "again"], ["Could you say", "that again"]],
    ["mean-this", "production", "Do you mean this one?", "您指的是这个吗？", "指着菜单确认对方的意思。", ["mean", "this one"], ["Do you mean", "this one"]],
    ["wait", "reception", "There is a fifteen minute wait.", "需要等十五分钟。", "没有空桌时听懂等待时间。", ["fifteen minute", "wait"], ["There is", "a fifteen minute wait"]],
    ["ready", "reception", "Your table is ready.", "您的桌子准备好了。", "等位结束时工作人员会这样说。", ["table", "ready"], ["Your table", "is ready"]],
    ["sold-out", "reception", "The pasta is sold out today.", "今天意面卖完了。", "听懂菜品售罄。", ["pasta", "sold out"], ["The pasta", "is sold out today"]],
    ["alternative", "reception", "We have risotto instead.", "我们有烩饭可以替代。", "工作人员推荐替代菜品。", ["risotto", "instead"], ["We have", "risotto instead"]],
    ["sparkling", "reception", "Would you like still or sparkling water?", "您要不带气的水还是气泡水？", "听懂两种饮用水选择。", ["still", "sparkling", "water"], ["Would you like", "still or sparkling water"]],
    ["contains-nuts", "reception", "This dish contains nuts.", "这道菜含有坚果。", "过敏时识别风险信息。", ["dish", "contains", "nuts"], ["This dish", "contains nuts"]],
    ["check-kitchen", "reception", "I will check with the kitchen.", "我会向厨房确认。", "工作人员需要进一步确认过敏信息。", ["check", "kitchen"], ["I will check", "with the kitchen"]],
    ["card", "reception", "You can pay by card at the counter.", "您可以在柜台刷卡。", "听懂付款方式和地点。", ["pay", "card", "counter"], ["You can pay by card", "at the counter"]]
  ]),
  "directions-tickets": pack("directions-tickets", [
    ["metro", "production", "How do I get to the metro?", "我怎么去地铁站？", "询问前往地铁的路线。", ["how", "metro"], ["How do I get", "to the metro"], "direction"],
    ["entrance", "production", "Where is entrance B?", "B 入口在哪里？", "寻找指定入口。", ["where", "entrance B"], ["Where is", "entrance B"], "entrance"],
    ["day-ticket", "production", "How much is a day ticket?", "一日票多少钱？", "询问交通票价格。", ["how much", "day ticket"], ["How much is", "a day ticket"], "ticket"],
    ["two-tickets", "production", "I need two tickets, please.", "我需要两张票。", "购买指定数量的票。", ["two", "tickets"], ["I need", "two tickets, please"]],
    ["validate", "production", "Do I need to validate this ticket?", "这张票需要激活吗？", "上车前确认是否需要验票。", ["validate", "ticket"], ["Do I need to validate", "this ticket"]],
    ["duration", "production", "How long does it take?", "需要多长时间？", "确认步行或乘车时间。", ["how long", "take"], ["How long", "does it take"], "time"],
    ["show", "production", "Could you show me?", "可以指给我看吗？", "听不懂方向时请对方展示。", ["show", "me"], ["Could you", "show me"]],
    ["again", "production", "Could you say the street name again?", "可以再说一遍街道名吗？", "没听清地名时使用。", ["street name", "again"], ["Could you say", "the street name again"], "repeat"],
    ["straight-left", "reception", "Go straight and turn left.", "直走，然后左转。", "最常见的两步方向说明。", ["straight", "left"], ["Go straight", "and turn left"]],
    ["opposite", "reception", "It is opposite the station.", "它在车站对面。", "识别参照位置。", ["opposite", "station"], ["It is opposite", "the station"]],
    ["ticket-price", "reception", "The day ticket is eight euros.", "一日票八欧元。", "听懂票价。", ["day ticket", "eight euros"], ["The day ticket", "is eight euros"]],
    ["valid-hours", "reception", "It is valid for twenty-four hours.", "有效期是二十四小时。", "听懂票的有效时间。", ["valid", "twenty-four hours"], ["It is valid", "for twenty-four hours"]],
    ["validate-before", "reception", "Validate it before you get on.", "上车前请激活车票。", "听懂验票要求。", ["validate", "before"], ["Validate it", "before you get on"]],
    ["last-entry", "reception", "Last entry is at five thirty.", "最后入场时间是五点半。", "景点入口的时间限制。", ["last entry", "five thirty"], ["Last entry", "is at five thirty"]],
    ["stop-moved", "reception", "The bus stop has moved across the road.", "公交站移到了马路对面。", "路线临时变化时使用。", ["bus stop", "moved", "across"], ["The bus stop has moved", "across the road"]],
    ["card-only", "reception", "This machine accepts cards only.", "这台机器只接受银行卡。", "自动售票机的付款限制。", ["machine", "cards only"], ["This machine", "accepts cards only"]]
  ]),
  "italy-high-speed-rail": pack("italy-high-speed-rail", [
    ["train", "production", "Is this the train to Florence?", "这是去佛罗伦萨的火车吗？", "上车前确认目的地。", ["train", "Florence"], ["Is this the train", "to Florence"], "train"],
    ["platform", "production", "Which platform is it?", "是哪个站台？", "查看大屏后仍不确定时询问。", ["which", "platform"], ["Which platform", "is it"], "platform"],
    ["carriage", "production", "Where is carriage four?", "四号车厢在哪里？", "寻找车厢位置。", ["where", "carriage four"], ["Where is", "carriage four"], "car"],
    ["seat", "production", "Is this seat 12A?", "这是 12A 座位吗？", "确认座位号。", ["seat", "12A"], ["Is this", "seat 12A"], "seat"],
    ["delayed", "production", "Is the train delayed?", "火车晚点了吗？", "大屏时间变化时确认。", ["train", "delayed"], ["Is the train", "delayed"], "delay"],
    ["connection", "production", "Will I miss my connection?", "我会错过下一趟车吗？", "晚点影响换乘时询问。", ["miss", "connection"], ["Will I miss", "my connection"]],
    ["screen", "production", "Could you show me on the screen?", "可以在屏幕上指给我看吗？", "听不清站台或车次时使用。", ["show", "screen"], ["Could you show me", "on the screen"]],
    ["need-help", "production", "I don't understand, but I need help.", "我听不懂，但我需要帮助。", "信息复杂时直接请求协助。", ["understand", "need help"], ["I don't understand", "but I need help"]],
    ["platform-nine", "reception", "Your train leaves from platform nine.", "您的火车从九号站台出发。", "听懂正常站台通知。", ["leaves", "platform nine"], ["Your train leaves", "from platform nine"]],
    ["platform-change", "reception", "The platform has changed to twelve.", "站台改到十二号了。", "识别临时站台变化。", ["platform", "changed", "twelve"], ["The platform has changed", "to twelve"]],
    ["delay-twenty", "reception", "The train is delayed by twenty minutes.", "火车晚点二十分钟。", "听懂晚点时长。", ["delayed", "twenty minutes"], ["The train is delayed", "by twenty minutes"]],
    ["cancelled", "reception", "This train has been cancelled.", "这趟火车取消了。", "识别取消通知。", ["train", "cancelled"], ["This train", "has been cancelled"]],
    ["carriage-front", "reception", "Carriage four is near the front.", "四号车厢靠近车头。", "听懂车厢方向。", ["carriage four", "front"], ["Carriage four", "is near the front"]],
    ["reserved", "reception", "That seat is reserved.", "那个座位已经被预订。", "坐错位置时可能听到。", ["seat", "reserved"], ["That seat", "is reserved"]],
    ["change-bologna", "reception", "You need to change trains in Bologna.", "您需要在博洛尼亚换车。", "听懂换乘地点。", ["change trains", "Bologna"], ["You need to change trains", "in Bologna"]],
    ["no-validate", "reception", "You do not need to validate this ticket.", "这张票不需要激活。", "电子票或指定车票的常见说明。", ["do not need", "validate"], ["You do not need", "to validate this ticket"]]
  ]),
  "swiss-mountain-transit": pack("swiss-mountain-transit", [
    ["zermatt", "production", "Which train goes to Zermatt?", "哪趟火车去采尔马特？", "寻找正确山区列车。", ["which train", "Zermatt"], ["Which train goes", "to Zermatt"], "train"],
    ["cable", "production", "Where is the cable car?", "缆车在哪里？", "寻找登山缆车。", ["where", "cable car"], ["Where is", "the cable car"], "cable"],
    ["gornergrat", "production", "Does this go to Gornergrat?", "这个去戈尔内格拉特吗？", "上车前确认山区目的地。", ["go", "Gornergrat"], ["Does this go", "to Gornergrat"], "gornergrat"],
    ["last-train", "production", "What is the last train back?", "最后一趟回程火车是几点？", "安排山区返程。", ["last train", "back"], ["What is", "the last train back"], "return"],
    ["lungern", "production", "Does this train stop at Lungern?", "这趟车停靠伦根吗？", "确认中途停靠站。", ["stop", "Lungern"], ["Does this train stop", "at Lungern"], "lungern"],
    ["airport", "production", "I need the train to Zurich Airport.", "我需要去苏黎世机场的火车。", "返程时寻找机场列车。", ["train", "Zurich Airport"], ["I need the train", "to Zurich Airport"], "zurich-airport"],
    ["slowly", "production", "Could you speak more slowly?", "可以说慢一点吗？", "山区站名听不清时使用。", ["speak", "slowly"], ["Could you speak", "more slowly"]],
    ["mean", "production", "Do you mean this one?", "您指的是这一趟吗？", "看着时刻表确认。", ["mean", "this one"], ["Do you mean", "this one"]],
    ["change-visp", "reception", "Change trains in Visp.", "请在菲斯普换车。", "前往采尔马特的常见换乘提示。", ["change trains", "Visp"], ["Change trains", "in Visp"]],
    ["platform-four", "reception", "The next train is on platform four.", "下一趟车在四号站台。", "听懂下一段站台。", ["next train", "platform four"], ["The next train", "is on platform four"]],
    ["cable-closed", "reception", "The cable car is closed today.", "缆车今天关闭。", "天气导致设施关闭时识别。", ["cable car", "closed"], ["The cable car", "is closed today"]],
    ["weather", "reception", "The weather is not safe this afternoon.", "今天下午天气不安全。", "听从山区天气安全建议。", ["weather", "not safe", "afternoon"], ["The weather is not safe", "this afternoon"]],
    ["last-ten", "reception", "The last train leaves at ten oh five.", "末班车十点零五分开。", "听懂末班车时间。", ["last train", "ten oh five"], ["The last train leaves", "at ten oh five"]],
    ["stops-lungern", "reception", "Yes, it stops at Lungern.", "是的，它停靠伦根。", "确认停靠站的正常回答。", ["stops", "Lungern"], ["Yes", "it stops at Lungern"]],
    ["lucerne-change", "reception", "You have one change before Lucerne.", "到卢塞恩前需要换乘一次。", "理解换乘次数。", ["one change", "Lucerne"], ["You have one change", "before Lucerne"]],
    ["ticket-valid", "reception", "Your ticket is valid on this train.", "您的票可以乘坐这趟车。", "确认车票有效。", ["ticket", "valid", "this train"], ["Your ticket is valid", "on this train"]]
  ]),
  "supermarket-groceries": pack("supermarket-groceries", [
    ["price", "production", "How much does this cost?", "这个多少钱？", "看不清价格标签时询问。", ["how much", "cost"], ["How much", "does this cost"], "price"],
    ["kilo", "production", "I would like one kilo, please.", "我想要一公斤。", "购买按重量计价的食品。", ["one kilo"], ["I would like", "one kilo, please"], "kilo"],
    ["bag", "production", "I need a bag, please.", "我需要一个袋子。", "结账时购买购物袋。", ["need", "bag"], ["I need", "a bag, please"], "bag"],
    ["card", "production", "Can I pay by card?", "可以刷卡吗？", "付款前确认刷卡。", ["pay", "card"], ["Can I pay", "by card"], "card"],
    ["receipt", "production", "Could I have the receipt?", "可以给我收据吗？", "付款后索取收据。", ["have", "receipt"], ["Could I have", "the receipt"], "receipt"],
    ["weigh", "production", "Where do I weigh this?", "我在哪里给这个称重？", "购买蔬果时寻找秤。", ["where", "weigh"], ["Where do I", "weigh this"]],
    ["show", "production", "Could you show me?", "可以指给我看吗？", "不会使用自助机器时请求展示。", ["show", "me"], ["Could you", "show me"]],
    ["help", "production", "I don't understand, but I need help.", "我听不懂，但我需要帮助。", "结账受阻时继续交流。", ["understand", "need help"], ["I don't understand", "but I need help"]],
    ["per-kilo", "reception", "The price is per kilo.", "价格是每公斤计算。", "识别称重商品价格。", ["price", "per kilo"], ["The price", "is per kilo"]],
    ["weigh-first", "reception", "Please weigh the fruit first.", "请先给水果称重。", "自助结账前的常见要求。", ["weigh", "fruit", "first"], ["Please weigh", "the fruit first"]],
    ["card-failed", "reception", "Your card did not go through.", "您的银行卡支付没有成功。", "识别刷卡失败。", ["card", "did not go through"], ["Your card", "did not go through"]],
    ["cash-only", "reception", "This checkout is cash only.", "这个收银台只收现金。", "识别付款限制。", ["checkout", "cash only"], ["This checkout", "is cash only"]],
    ["bag-cost", "reception", "Bags cost twenty cents.", "购物袋二十欧分一个。", "听懂购物袋收费。", ["bags", "twenty cents"], ["Bags cost", "twenty cents"]],
    ["receipt-below", "reception", "Your receipt is below the screen.", "您的收据在屏幕下方。", "自助结账后寻找收据。", ["receipt", "below", "screen"], ["Your receipt is", "below the screen"]],
    ["self-checkout", "reception", "You can use the self-checkout.", "您可以使用自助结账。", "排队时工作人员可能分流。", ["use", "self-checkout"], ["You can use", "the self-checkout"]],
    ["scan-again", "reception", "Please scan the barcode again.", "请重新扫描条形码。", "商品未识别时按提示操作。", ["scan", "barcode", "again"], ["Please scan", "the barcode again"]]
  ]),
  "urgent-help": pack("urgent-help", [
    ["lost", "production", "I am lost and separated from my group.", "我迷路了，和同伴走散了。", "走散后清楚说明情况。", ["lost", "separated", "group"], ["I am lost", "and separated from my group"], "lost-separated"],
    ["battery", "production", "My phone is out of battery.", "我的手机没电了。", "无法联系同行人时说明。", ["phone", "out of battery"], ["My phone", "is out of battery"], "phone"],
    ["bag", "production", "My bag is missing.", "我的包不见了。", "报告物品遗失。", ["bag", "missing"], ["My bag", "is missing"], "bag"],
    ["doctor", "production", "I need a doctor.", "我需要医生。", "身体不适时直接求助。", ["need", "doctor"], ["I need", "a doctor"], "medical"],
    ["police", "production", "Where can I find a police officer?", "在哪里可以找到警察？", "需要警方协助时询问。", ["where", "police officer"], ["Where can I find", "a police officer"], "police"],
    ["toilet", "production", "Where is the nearest toilet?", "最近的洗手间在哪里？", "紧急寻找洗手间。", ["nearest", "toilet"], ["Where is", "the nearest toilet"], "toilet"],
    ["call", "production", "Please call 112. I need help.", "请拨打 112，我需要帮助。", "发生紧急危险时请求报警。", ["call 112", "need help"], ["Please call 112", "I need help"], "emergency"],
    ["understand", "production", "I don't understand, but I need help.", "我听不懂，但我需要帮助。", "语言困难时保持求助。", ["understand", "need help"], ["I don't understand", "but I need help"]],
    ["stay-calm", "reception", "Please stay calm.", "请保持冷静。", "工作人员开始帮助时常说。", ["stay", "calm"], ["Please", "stay calm"]],
    ["location", "reception", "Can you tell me your location?", "您能告诉我您的位置吗？", "报警或求助时必须听懂。", ["tell", "location"], ["Can you tell me", "your location"]],
    ["operator", "reception", "Emergency services, what happened?", "这里是紧急服务，发生了什么？", "拨打紧急电话后的第一句。", ["emergency services", "what happened"], ["Emergency services", "what happened"]],
    ["ambulance", "reception", "An ambulance is on the way.", "救护车正在赶来。", "确认救援已经出发。", ["ambulance", "on the way"], ["An ambulance", "is on the way"]],
    ["pharmacy", "reception", "The pharmacy is around the corner.", "药店就在拐角附近。", "听懂药店方向。", ["pharmacy", "around the corner"], ["The pharmacy", "is around the corner"]],
    ["station", "reception", "The police station is two streets away.", "警察局在两条街以外。", "听懂警察局距离。", ["police station", "two streets"], ["The police station", "is two streets away"]],
    ["charge", "reception", "You can charge your phone here.", "您可以在这里给手机充电。", "确认充电位置。", ["charge", "phone", "here"], ["You can charge", "your phone here"]],
    ["description", "reception", "Please describe your missing bag.", "请描述一下丢失的包。", "报失时听懂对方要求。", ["describe", "missing bag"], ["Please describe", "your missing bag"]]
  ])
} as const;
